# see https://symfony.com/doc/current/reference/configuration/framework.html
# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    # default_locale: fr
    # translator:
    #     default_path: '%kernel.project_dir%/translations'
    #     fallbacks:
    #         - fr   
    cache: 
        app: cache.adapter.filesystem 
        system: cache.adapter.system 
        directory: '%kernel.cache_dir%/pools'

    translator:
        enabled: false
    #     fallbacks: ['fr']
    # profiler:
    #     enabled: true
    #     collect: false
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        cache: 
            app: cache.adapter.filesystem 
            system: cache.adapter.system 
            directory: '%kernel.cache_dir%/pools'