knp_paginator:
    page_range: 5                      # Page range used in pagination control
    default_options:
        page_name: page                # Page query parameter name
        sort_field_name: sort          # Sort field query parameter name
        sort_direction_name: direction # Sort direction query parameter name
        distinct: true                 # Ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'  # Sliding pagination template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # Sortable link template
