when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false
        # excluded_ajax_paths: ^/((app(_[\\w]+)?\\.php/)?_wdt|css|images|js)/
        excluded_ajax_paths: ^/((app(_[\\w]+)?\\.php/)?_wdt|_profiler)/
        
    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
