# config/routes.yaml
# Consolidated controller configuration
controllers:
    resource: ../src/Controller/ # Path to your controller directory
    # namespace: App\Controller  # Namespace for your controllers
    type: attribute             # Default controller type (can be adjusted if needed)

index:
    path: /
    controller: App\Controller\MainController::home
    # controller: App\Controller\ProduitController::index
    # controller: App\Controller\SousCategorieController::index
    # controller: App\Controller\login_registerController::index
    
# images:
#     path: /images/
#     controller: App\Controller\ImageController::index
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# app_register:
#     path: /register
#     controller: App\Controller\SecurityController::register

app_evenements:
    path: /
    controller: App\Controller\MainController::index


# reservation_new:
#   path: /reservation/new
#   controller: App\Controller\ReservationController::new

# reservation_confirmation:
#   path: /reservation/confirmation/{id}
#   controller: App\Controller\ReservationController::confirmation
    # controller: App\Controller\ProduitController::index

favicon:
    path: /favicon.ico
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirect
    defaults:
        path: /public/favicon.ico
        permanent: true
