# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

# parameters: This section is used to define various parameters that can be used throughout the configuration.
# images_directory: This is the name of the parameter being defined.
# ‘%kernel.project_dir%/assets/images’: This is the value of the images_directory parameter. It uses a placeholder %kernel.project_dir% which represents the root directory of the Symfony project. The full path would be the root directory followed by /assets/images.
parameters:
    images_directory: '%kernel.project_dir%/assets/images'  

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Rendre les classes de src/ disponibles comme services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # Définition du service ImageUploader
    App\Service\ImageUploader:
        arguments:
            $targetDirectory: '%images_directory%'

    # Ajoute des définitions de services supplémentaires si besoin
    App\Controller\ProduitController:
        arguments: []
 
    App\Twig\AppExtension:
        tags: ['twig.extension']
